## Determing correlations and independences

In [0]:
import pandas as pd
import numpy as np

#Cleaning the tables

tab2 = pd.read_csv('Table2.csv')
tab2.drop(['Values'],inplace=True,axis=1,errors='ignore')
# print(tab2)
tab2_clean = np.zeros((tab2.shape[0],tab2.shape[1]))
for i in range(len(tab2)):
    for j in range(len(tab2.iloc[i])):
        if(not pd.isnull(tab2.iloc[i][j])):
            t = tab2.iloc[i][j].split("%")[0]
            tab2_clean[i][j] = float(t)/100
print(tab2_clean)        

[[0.78  0.275 0.18  0.715 0.375 0.015]
 [0.015 0.32  0.66  0.105 0.11  0.32 ]
 [0.055 0.025 0.16  0.01  0.105 0.14 ]
 [0.15  0.17  0.    0.17  0.41  0.315]
 [0.    0.21  0.    0.    0.    0.21 ]]


In [0]:
tab3 = pd.read_csv('Table3.csv')
tab3.drop(['x1'],inplace=True,axis=1,errors = 'ignore')
# print(tab3)
tab3_clean = np.zeros((tab3.shape[0],tab3.shape[1]))
for i in range(len(tab3)):
    for j in range(len(tab3.iloc[i])):
        t = tab3.iloc[i][j].split("%")[0]
        tab3_clean[i][j] = float(t)/100
print(tab3_clean)       


    

[[0.78  0.015 0.055 0.15 ]
 [0.231 0.666 0.455 0.4  ]
 [0.365 0.    0.091 0.2  ]
 [0.026 0.    0.    0.033]
 [0.173 0.    0.182 0.167]
 [0.205 0.333 0.273 0.2  ]
 [0.737 1.    0.727 0.567]
 [0.077 0.    0.273 0.2  ]
 [0.013 0.    0.    0.   ]
 [0.173 0.    0.    0.233]
 [0.019 0.    0.    0.   ]
 [0.282 0.666 0.545 0.4  ]
 [0.128 0.333 0.091 0.2  ]
 [0.352 0.    0.182 0.2  ]
 [0.218 0.    0.182 0.2  ]]


In [0]:
#Calculating correlations for Table 3


sum = 0
for i in range(4):
    for j in range(1,6):
        sum = sum + abs(tab3_clean[0][i]*((tab3_clean[j][i]) - (tab2_clean[j-1][1])))        
print("Correlation(x2,x1): ",sum)  

sum = 0
for i in range(4):
    for j in range(6,10):
        sum = sum + abs(tab3_clean[0][i]*((tab3_clean[j][i]) - (tab2_clean[j-6][3])))
print("Correlation(x4,x1): ",sum)  


sum = 0
for i in range(4):
    for j in range(10,15):
        sum = sum + abs(tab3_clean[0][i]*((tab3_clean[j][i]) - (tab2_clean[j-10][5])))
        
print("Correlation(x6,x1): ",sum)  

def is_independent(X, Y, Zs=[], significance_level=0.05):
    return est.test_conditional_independence(X, Y, Zs)[1] >= significance_level
print(is_independent('x2', 'x3'))    #dependent


Correlation(x2,x1):  0.15977
Correlation(x4,x1):  0.11943
Correlation(x6,x1):  0.16015500000000008
False


In [0]:
tab4 = pd.read_csv('Table4.csv')
tab4.drop(['x2'],inplace=True,axis=1,errors = 'ignore')
tab4_clean = np.zeros((tab4.shape[0],tab4.shape[1]))
for i in range(len(tab4)):
    for j in range(len(tab4.iloc[i])):
        t = tab4.iloc[i][j].split("%")[0]
        tab4_clean[i][j] = float(t)/100
print(tab4_clean)   

[[0.275 0.32  0.025 0.17  0.21 ]
 [0.127 0.266 0.2   0.176 0.119]
 [0.745 0.656 0.8   0.706 0.5  ]
 [0.127 0.078 0.    0.118 0.381]
 [0.418 0.344 0.6   0.382 0.334]
 [0.073 0.109 0.4   0.147 0.095]
 [0.109 0.125 0.    0.118 0.071]
 [0.4   0.422 0.    0.353 0.5  ]]


In [0]:
sum = 0
for i in range(5):
    for j in range(1,4):
        sum = sum + abs(tab4_clean[0][i]*((tab4_clean[j][i]) - (tab2_clean[j-1][2])))
print("Correlation(x3,x2): ",sum)  

sum = 0
for i in range(5):
    for j in range(4,8):
        sum = sum + abs(tab4_clean[0][i]*((tab4_clean[j][i]) - (tab2_clean[j-4][4])))
print("Correlation(x5,x2): ",sum)  

Correlation(x3,x2):  0.21852500000000002
Correlation(x5,x2):  0.12926000000000004


In [0]:
tab5 = pd.read_csv('Table5.csv')
tab5.drop(['x3'],inplace=True,axis=1,errors = 'ignore')
tab5_clean = np.zeros((tab5.shape[0],tab5.shape[1]))
for i in range(len(tab5)):
    for j in range(len(tab5.iloc[i])):
        t = tab5.iloc[i][j].split("%")[0]
        tab5_clean[i][j] = float(t)/100
print(tab5_clean)   

[[0.18   0.66   0.16  ]
 [0.194  0.311  0.219 ]
 [0.472  0.318  0.156 ]
 [0.028  0.0303 0.    ]
 [0.167  0.182  0.125 ]
 [0.139  0.159  0.5   ]
 [0.361  0.394  0.313 ]
 [0.083  0.114  0.125 ]
 [0.222  0.091  0.031 ]
 [0.333  0.402  0.531 ]
 [0.     0.023  0.    ]
 [0.389  0.318  0.25  ]
 [0.083  0.152  0.156 ]
 [0.361  0.303  0.313 ]
 [0.167  0.204  0.281 ]]


In [0]:
sum = 0
for i in range(3):
    for j in range(1,6):
        sum = sum + abs(tab5_clean[0][i]*((tab5_clean[j][i]) - (tab2_clean[j-1][1])))
print("Correlation(x2,x3): ",sum)  


sum = 0
for i in range(3):
    for j in range(6,10):
        sum = sum + abs(tab5_clean[0][i]*((tab5_clean[j][i]) - (tab2_clean[j-6][4])))
print("Correlation(x5,x3): ",sum)  


sum = 0
for i in range(3):
    for j in range(10,15):
        sum = sum + abs(tab5_clean[0][i]*((tab5_clean[j][i]) - (tab2_clean[j-10][5])))
print("Correlation(x6,x3): ",sum)  

Correlation(x2,x3):  0.218758
Correlation(x5,x3):  0.11551999999999996
Correlation(x6,x3):  0.09564


In [0]:
tab6 = pd.read_csv('Table6.csv')
tab6.drop(['x4'],inplace=True,axis=1,errors = 'ignore')
tab6_clean = np.zeros((tab6.shape[0],tab6.shape[1]))
for i in range(len(tab6)):
    for j in range(len(tab6.iloc[i])):
        t = tab6.iloc[i][j].split("%")[0]
        tab6_clean[i][j] = float(t)/100
print(tab6_clean)   

[[0.715 0.105 0.01  0.17 ]
 [0.804 0.571 1.    0.794]
 [0.021 0.    0.    0.   ]
 [0.056 0.143 0.    0.   ]
 [0.119 0.286 0.    0.206]
 [0.308 0.238 0.    0.176]
 [0.322 0.286 1.    0.323]
 [0.028 0.    0.    0.029]
 [0.154 0.19  0.    0.235]
 [0.196 0.286 0.    0.235]
 [0.021 0.    0.    0.   ]
 [0.28  0.571 0.    0.353]
 [0.154 0.143 0.    0.088]
 [0.329 0.19  0.5   0.323]
 [0.217 0.095 0.5   0.235]]


In [0]:
sum = 0
for i in range(4):
    for j in range(1,5):
        sum = sum + abs(tab6_clean[0][i]*((tab6_clean[j][i]) - (tab2_clean[j-1][0])))
print("Correlation(x1,x4): ",sum)  


sum = 0
for i in range(4):
    for j in range(5,10):
        sum = sum + abs(tab6_clean[0][i]*((tab6_clean[j][i]) - (tab2_clean[j-5][1])))
print("Correlation(x2,x4): ",sum) 

sum = 0
for i in range(4):
    for j in range(10,15):
        sum = sum + abs(tab6_clean[0][i]*((tab6_clean[j][i]) - (tab2_clean[j-10][5])))
print("Correlation(x6,x4): ",sum) 



Correlation(x1,x4):  0.11956999999999998
Correlation(x2,x4):  0.11569999999999998
Correlation(x6,x4):  0.14346999999999993


In [0]:
tab7 = pd.read_csv('Table7.csv')
tab7.drop(['x5'],inplace=True,axis=1,errors = 'ignore')
tab7_clean = np.zeros((tab7.shape[0],tab7.shape[1]))
for i in range(len(tab7)):
    for j in range(len(tab7.iloc[i])):
        t = tab7.iloc[i][j].split("%")[0]
        tab7_clean[i][j] = float(t)/100
print(tab7_clean)   

[[0.375 0.11  0.105 0.41 ]
 [0.307 0.182 0.286 0.268]
 [0.293 0.318 0.381 0.329]
 [0.04  0.091 0.    0.   ]
 [0.173 0.227 0.19  0.146]
 [0.182 0.182 0.143 0.256]
 [0.173 0.136 0.381 0.146]
 [0.693 0.682 0.571 0.646]
 [0.133 0.182 0.048 0.207]]


In [0]:
sum = 0
for i in range(4):
    for j in range(1,6):
        sum = sum + abs(tab7_clean[0][i]*((tab7_clean[j][i]) - (tab2_clean[j-1][1])))
print("Correlation(x2,x5): ",sum) 


sum = 0
for i in range(4):
    for j in range(6,9):
        sum = sum + abs(tab7_clean[0][i]*((tab7_clean[j][i]) - (tab2_clean[j-6][2])))
print("Correlation(x6,x5): ",sum) 

Correlation(x2,x5):  0.131265
Correlation(x6,x5):  0.115965


In [0]:
tab8 = pd.read_csv('Table8.csv')
tab8.drop(['x6'],inplace=True,axis=1,errors = 'ignore')
tab8_clean = np.zeros((tab8.shape[0],tab8.shape[1]))
for i in range(len(tab8)):
    for j in range(len(tab8.iloc[i])):
        t = tab8.iloc[i][j].split("%")[0]
        tab8_clean[i][j] = float(t)/100
print(tab8_clean)   

[[0.015 0.32  0.14  0.315 0.21 ]
 [1.    0.687 0.714 0.8   0.809]
 [0.    0.031 0.036 0.    0.   ]
 [0.    0.142 0.036 0.    0.048]
 [0.    0.14  0.214 0.2   0.143]
 [0.    0.281 0.214 0.317 0.262]
 [0.333 0.296 0.392 0.317 0.309]
 [0.    0.    0.    0.079 0.   ]
 [0.666 0.234 0.142 0.095 0.167]
 [0.    0.187 0.25  0.19  0.262]
 [0.173 0.136 0.381 0.146 0.143]
 [0.693 0.682 0.571 0.646 0.643]
 [0.133 0.182 0.041 0.207 0.214]
 [1.    0.625 0.786 0.746 0.738]
 [0.    0.187 0.107 0.063 0.048]
 [0.    0.    0.    0.016 0.024]
 [0.    0.187 0.107 0.175 0.19 ]]


In [0]:
sum = 0
for i in range(5):
    for j in range(1,5):
        sum = sum + abs(tab8_clean[0][i]*((tab8_clean[j][i]) - (tab2_clean[j-1][0])))
print("Correlation(x1,x6): ",sum) 

sum = 0
for i in range(5):
    for j in range(5,10):
        sum = sum + abs(tab8_clean[0][i]*((tab8_clean[j][i]) - (tab2_clean[j-5][1])))
print("Correlation(x2,x6): ",sum) 

sum = 0
for i in range(5):
    for j in range(10,13):
        sum = sum + abs(tab8_clean[0][i]*((tab8_clean[j][i]) - (tab2_clean[j-10][2])))
print("Correlation(x3,x6): ",sum) 

sum = 0
for i in range(5):
    for j in range(13,17):
        sum = sum + abs((tab8_clean[0][i]*tab8_clean[j][i]) - (tab8_clean[0][i]*tab2_clean[j-13][3]))
print("Correlation(x4,x6): ",sum) 

Correlation(x1,x6):  0.15259999999999999
Correlation(x2,x6):  0.17531500000000005
Correlation(x3,x6):  0.13903000000000001
Correlation(x4,x6):  0.14307000000000003


In [0]:
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianModel
from pgmpy.sampling import BayesianModelSampling
from pgmpy.estimators import K2Score


#Creating Conditional Probability Distribution tables
x21_cpd = TabularCPD('x2',5,[tab3_clean[1,:],tab3_clean[2,:],tab3_clean[3,:],tab3_clean[4,:],tab3_clean[5,:]],evidence=['x1'],evidence_card=[4])
print(x21_cpd)

x41_cpd=  TabularCPD('x4',4,[tab3_clean[6,:],tab3_clean[7,:],tab3_clean[8,:],tab3_clean[9,:]],evidence=['x1'],evidence_card=[4])
print(x41_cpd)

x61_cpd=  TabularCPD('x6',5,[tab3_clean[10,:],tab3_clean[11,:],tab3_clean[12,:],tab3_clean[13,:],tab3_clean[14,:]],evidence=['x1'],evidence_card=[4])
print(x61_cpd)

print(x21_cpd.is_valid_cpd())
print(x41_cpd.is_valid_cpd())
print(x61_cpd.is_valid_cpd())

+------+----------------------+---------------------+-------+---------------------+
| x1   | x1_0                 | x1_1                | x1_2  | x1_3                |
+------+----------------------+---------------------+-------+---------------------+
| x2_0 | 0.231                | 0.6659999999999999  | 0.455 | 0.4                 |
+------+----------------------+---------------------+-------+---------------------+
| x2_1 | 0.365                | 0.0                 | 0.091 | 0.2                 |
+------+----------------------+---------------------+-------+---------------------+
| x2_2 | 0.026000000000000002 | 0.0                 | 0.0   | 0.033               |
+------+----------------------+---------------------+-------+---------------------+
| x2_3 | 0.17300000000000001  | 0.0                 | 0.182 | 0.16699999999999998 |
+------+----------------------+---------------------+-------+---------------------+
| x2_4 | 0.205                | 0.33299999999999996 | 0.273 | 0.2           

In [0]:
x32_cpd = TabularCPD('x3',3,[tab4_clean[1,:],tab4_clean[2,:],tab4_clean[3,:]],evidence=['x2'],evidence_card=[5])
print(x32_cpd)

x52_cpd = TabularCPD('x5',4,[tab4_clean[4,:],tab4_clean[5,:],tab4_clean[6,:],tab4_clean[7,:]],evidence=['x2'],evidence_card=[5])
print(x52_cpd)

print(x32_cpd.is_valid_cpd())
print(x52_cpd.is_valid_cpd())

+------+-------+--------------------+------+---------------------+---------------------+
| x2   | x2_0  | x2_1               | x2_2 | x2_3                | x2_4                |
+------+-------+--------------------+------+---------------------+---------------------+
| x3_0 | 0.127 | 0.266              | 0.2  | 0.17600000000000002 | 0.11900000000000001 |
+------+-------+--------------------+------+---------------------+---------------------+
| x3_1 | 0.745 | 0.6559999999999999 | 0.8  | 0.706               | 0.5                 |
+------+-------+--------------------+------+---------------------+---------------------+
| x3_2 | 0.127 | 0.078              | 0.0  | 0.11800000000000001 | 0.381               |
+------+-------+--------------------+------+---------------------+---------------------+
+------+-------+---------------------+------+---------------------+---------------------+
| x2   | x2_0  | x2_1                | x2_2 | x2_3                | x2_4                |
+------+-------+---

In [0]:
x23_cpd = TabularCPD('x2',5,[tab5_clean[1,:],tab5_clean[2,:],tab5_clean[3,:],tab5_clean[4,:],tab5_clean[5,:]],evidence=['x3'],evidence_card=[3])
print(x23_cpd)

x53_cpd = TabularCPD('x5',4,[tab5_clean[6,:],tab5_clean[7,:],tab5_clean[8,:],tab5_clean[9,:]],evidence=['x3'],evidence_card=[3])
print(x53_cpd)

x63_cpd = TabularCPD('x6',5,[tab5_clean[10,:],tab5_clean[11,:],tab5_clean[12,:],tab5_clean[13,:],tab5_clean[14,:]],evidence=['x3'],evidence_card=[3])
print(x63_cpd)

print(x23_cpd.is_valid_cpd())
print(x53_cpd.is_valid_cpd())
print(x63_cpd.is_valid_cpd())

+------+----------------------+----------------------+---------------------+
| x3   | x3_0                 | x3_1                 | x3_2                |
+------+----------------------+----------------------+---------------------+
| x2_0 | 0.19399999999999998  | 0.311                | 0.21899999999999997 |
+------+----------------------+----------------------+---------------------+
| x2_1 | 0.47200000000000003  | 0.318                | 0.156               |
+------+----------------------+----------------------+---------------------+
| x2_2 | 0.027999999999999997 | 0.030299999999999997 | 0.0                 |
+------+----------------------+----------------------+---------------------+
| x2_3 | 0.16699999999999998  | 0.182                | 0.125               |
+------+----------------------+----------------------+---------------------+
| x2_4 | 0.139                | 0.159                | 0.5                 |
+------+----------------------+----------------------+---------------------+

In [0]:
x14_cpd = TabularCPD('x1',4,[tab6_clean[1,:],tab6_clean[2,:],tab6_clean[3,:],tab6_clean[4,:]],evidence=['x4'],evidence_card=[4])
print(x14_cpd)

x24_cpd = TabularCPD('x2',5,[tab6_clean[5,:],tab6_clean[6,:],tab6_clean[7,:],tab6_clean[8,:],tab6_clean[9,:]],evidence=['x4'],evidence_card=[4])
print(x24_cpd)

x64_cpd = TabularCPD('x6',5,[tab6_clean[10,:],tab6_clean[11,:],tab6_clean[12,:],tab6_clean[13,:],tab6_clean[14,:]],evidence=['x4'],evidence_card=[4])
print(x64_cpd)

print(x14_cpd.is_valid_cpd())
print(x24_cpd.is_valid_cpd())
print(x64_cpd.is_valid_cpd())

+------+----------------------+---------------------+------+---------------------+
| x4   | x4_0                 | x4_1                | x4_2 | x4_3                |
+------+----------------------+---------------------+------+---------------------+
| x1_0 | 0.804                | 0.5710000000000001  | 1.0  | 0.794               |
+------+----------------------+---------------------+------+---------------------+
| x1_1 | 0.021                | 0.0                 | 0.0  | 0.0                 |
+------+----------------------+---------------------+------+---------------------+
| x1_2 | 0.055999999999999994 | 0.14300000000000002 | 0.0  | 0.0                 |
+------+----------------------+---------------------+------+---------------------+
| x1_3 | 0.11900000000000001  | 0.28600000000000003 | 0.0  | 0.20600000000000002 |
+------+----------------------+---------------------+------+---------------------+
+------+----------------------+---------------------+------+----------------------+
| x

In [0]:
x25_cpd = TabularCPD('x2',5,[tab7_clean[1,:],tab7_clean[2,:],tab7_clean[3,:],tab7_clean[4,:],tab7_clean[5,:]],evidence=['x5'],evidence_card=[4])
print(x25_cpd)


x35_cpd = TabularCPD('x3',3,[tab7_clean[6,:],tab7_clean[7,:],tab7_clean[8,:]],evidence=['x5'],evidence_card=[4])
print(x35_cpd)

print(x25_cpd.is_valid_cpd())
print(x35_cpd.is_valid_cpd())

+------+---------------------+---------------------+---------------------+---------------------+
| x5   | x5_0                | x5_1                | x5_2                | x5_3                |
+------+---------------------+---------------------+---------------------+---------------------+
| x2_0 | 0.307               | 0.182               | 0.28600000000000003 | 0.268               |
+------+---------------------+---------------------+---------------------+---------------------+
| x2_1 | 0.293               | 0.318               | 0.381               | 0.32899999999999996 |
+------+---------------------+---------------------+---------------------+---------------------+
| x2_2 | 0.04                | 0.091               | 0.0                 | 0.0                 |
+------+---------------------+---------------------+---------------------+---------------------+
| x2_3 | 0.17300000000000001 | 0.22699999999999998 | 0.19                | 0.146               |
+------+---------------------+

In [0]:
x16_cpd = TabularCPD('x1',4,[tab8_clean[1,:],tab8_clean[2,:],tab8_clean[3,:],tab8_clean[4,:]],evidence=['x6'],evidence_card=[5])
print(x16_cpd)

x26_cpd = TabularCPD('x2',5,[tab8_clean[5,:],tab8_clean[6,:],tab8_clean[7,:],tab8_clean[8,:],tab8_clean[9,:]],evidence=['x6'],evidence_card=[5])
print(x26_cpd)

x36_cpd = TabularCPD('x3',3,[tab8_clean[10,:],tab8_clean[11,:],tab8_clean[12,:]],evidence=['x6'],evidence_card=[5])
print(x36_cpd)

x46_cpd = TabularCPD('x4',4,[tab8_clean[13,:],tab8_clean[14,:],tab8_clean[15,:],tab8_clean[16,:]],evidence=['x6'],evidence_card=[5])
print(x46_cpd)

print(x16_cpd.is_valid_cpd())
print(x26_cpd.is_valid_cpd())
print(x36_cpd.is_valid_cpd())
print(x46_cpd.is_valid_cpd())

+------+------+-------+----------------------+------+---------------------+
| x6   | x6_0 | x6_1  | x6_2                 | x6_3 | x6_4                |
+------+------+-------+----------------------+------+---------------------+
| x1_0 | 1.0  | 0.687 | 0.7140000000000001   | 0.8  | 0.809               |
+------+------+-------+----------------------+------+---------------------+
| x1_1 | 0.0  | 0.031 | 0.036000000000000004 | 0.0  | 0.0                 |
+------+------+-------+----------------------+------+---------------------+
| x1_2 | 0.0  | 0.142 | 0.036000000000000004 | 0.0  | 0.048               |
+------+------+-------+----------------------+------+---------------------+
| x1_3 | 0.0  | 0.14  | 0.214                | 0.2  | 0.14300000000000002 |
+------+------+-------+----------------------+------+---------------------+
+------+---------------------+---------------------+-------+-------+---------------------+
| x6   | x6_0                | x6_1                | x6_2  | x6_3  | x6_4

In [0]:
x1_cpd = TabularCPD('x1',4,[tab2_clean[0:4,0]])
print(x1_cpd)

x2_cpd = TabularCPD('x2',5,[tab2_clean[0:5,1]])
print(x2_cpd)

x3_cpd = TabularCPD('x3',3,[tab2_clean[0:3,2]])
print(x3_cpd)

x4_cpd = TabularCPD('x4',4,[tab2_clean[0:4,3]])
print(x4_cpd)

x5_cpd = TabularCPD('x5',4,[tab2_clean[0:4,4]])
print(x5_cpd)

x6_cpd = TabularCPD('x6',5,[tab2_clean[0:5,5]])
print(x6_cpd)

print(x1_cpd.is_valid_cpd())
print(x2_cpd.is_valid_cpd())
print(x3_cpd.is_valid_cpd())
print(x4_cpd.is_valid_cpd())
print(x5_cpd.is_valid_cpd())
print(x6_cpd.is_valid_cpd())

+------+-------+
| x1_0 | 0.78  |
+------+-------+
| x1_1 | 0.015 |
+------+-------+
| x1_2 | 0.055 |
+------+-------+
| x1_3 | 0.15  |
+------+-------+
+------+-------+
| x2_0 | 0.275 |
+------+-------+
| x2_1 | 0.32  |
+------+-------+
| x2_2 | 0.025 |
+------+-------+
| x2_3 | 0.17  |
+------+-------+
| x2_4 | 0.21  |
+------+-------+
+------+------+
| x3_0 | 0.18 |
+------+------+
| x3_1 | 0.66 |
+------+------+
| x3_2 | 0.16 |
+------+------+
+------+-------+
| x4_0 | 0.715 |
+------+-------+
| x4_1 | 0.105 |
+------+-------+
| x4_2 | 0.01  |
+------+-------+
| x4_3 | 0.17  |
+------+-------+
+------+-------+
| x5_0 | 0.375 |
+------+-------+
| x5_1 | 0.11  |
+------+-------+
| x5_2 | 0.105 |
+------+-------+
| x5_3 | 0.41  |
+------+-------+
+------+-------+
| x6_0 | 0.015 |
+------+-------+
| x6_1 | 0.32  |
+------+-------+
| x6_2 | 0.14  |
+------+-------+
| x6_3 | 0.315 |
+------+-------+
| x6_4 | 0.21  |
+------+-------+
True
True
True
True
True
True


## Baysian network construction and inference

In [0]:
network= BayesianModel()
network.add_nodes_from(['x1','x2','x3','x4','x5','x6'])
network.add_edges_from([('x1','x2'),('x1','x4'),('x1','x6'),('x2','x5'),('x2','x3')])
network.add_cpds(x1_cpd,x21_cpd,x41_cpd,x61_cpd,x52_cpd,x32_cpd)
network.check_model()
infer = BayesianModelSampling(network)
inference=infer.forward_sample(size=1000, return_type='dataframe')
print(inference)
k2 = K2Score(inference)
print(str(k2.score(network)))



# esti = ConstraintBasedEstimator(inference)
# print(esti.estimate(significance_level=0.9).edges())




     x1  x2  x5  x3  x4  x6
0     0   1   0   1   1   4
1     0   0   1   1   0   4
2     3   4   0   1   1   2
3     0   3   1   1   3   1
4     3   2   0   0   1   4
5     0   1   2   1   0   1
6     0   1   3   1   0   2
7     0   3   3   1   0   3
8     0   2   0   1   0   2
9     0   0   2   0   3   1
10    3   1   0   1   0   3
11    0   0   0   1   3   4
12    0   3   3   1   0   1
13    0   1   3   2   0   2
14    0   0   3   1   0   3
15    0   0   3   1   3   3
16    0   0   0   0   0   1
17    2   3   3   1   0   3
18    0   4   3   1   0   1
19    0   1   3   2   0   2
20    0   4   2   1   0   2
21    2   0   3   1   0   1
22    2   0   3   1   1   1
23    3   3   0   0   0   2
24    0   1   0   1   0   3
25    0   4   3   1   0   2
26    0   4   3   2   0   3
27    0   0   3   1   0   1
28    3   1   0   0   0   3
29    2   4   0   1   0   1
..   ..  ..  ..  ..  ..  ..
970   0   1   0   1   3   2
971   0   3   1   1   0   1
972   2   0   0   1   1   1
973   0   3   1   2 

In [0]:
network1= BayesianModel()
network1.add_nodes_from(['x1','x2','x3','x4','x5','x6'])
network1.add_edges_from([('x2','x3'),('x2','x5'),('x3','x6'),('x6','x1'),('x6','x4')])
network1.add_cpds(x2_cpd,x32_cpd,x52_cpd,x63_cpd,x16_cpd,x46_cpd)
network1.check_model()
infer1 = BayesianModelSampling(network1)
inference1=infer1.forward_sample(size=1000, return_type='dataframe')
print(inference1)
k2_1 = K2Score(inference1)
print(str(k2_1.score(network1)))


     x2  x3  x6  x4  x5  x1
0     1   0   4   0   3   0
1     3   1   3   1   3   0
2     1   1   4   0   0   0
3     1   0   4   3   1   0
4     0   1   4   3   0   0
5     4   1   1   0   0   3
6     3   1   1   3   3   0
7     3   1   3   0   3   0
8     1   1   2   0   0   0
9     1   1   2   0   0   0
10    0   1   4   0   3   0
11    1   1   3   0   3   0
12    1   0   3   0   0   0
13    1   1   1   0   3   0
14    0   0   1   0   0   1
15    0   0   3   1   3   0
16    4   2   1   0   3   0
17    4   2   4   3   0   0
18    4   2   3   3   1   0
19    1   1   1   0   2   0
20    0   0   3   0   3   0
21    0   1   1   0   1   0
22    4   2   1   0   3   0
23    0   2   1   1   0   0
24    0   1   2   0   3   3
25    3   1   4   0   3   0
26    4   1   1   0   0   3
27    1   1   3   0   0   0
28    1   1   1   0   1   0
29    2   1   1   0   0   0
..   ..  ..  ..  ..  ..  ..
970   1   1   2   0   3   0
971   1   0   3   3   3   0
972   0   1   4   0   3   0
973   1   1   2   0 

In [0]:
network2= BayesianModel()
network2.add_nodes_from(['x1','x2','x3','x4','x5','x6'])
network2.add_edges_from([('x1','x4'),('x1','x2'),('x2','x3'),('x4','x6'),('x3','x5')])
network2.add_cpds(x1_cpd,x41_cpd,x21_cpd,x32_cpd,x64_cpd,x53_cpd)
network2.check_model()
infer2 = BayesianModelSampling(network2)
inference2=infer2.forward_sample(size=1000, return_type='dataframe')
print(inference2)
k2_2 = K2Score(inference2)
print(str(k2_2.score(network2)))


     x1  x4  x6  x2  x3  x5
0     1   0   4   0   1   1
1     0   3   2   0   1   2
2     0   0   4   0   1   3
3     2   0   4   4   2   3
4     0   0   4   0   1   3
5     0   0   3   0   2   0
6     0   0   3   3   1   1
7     0   3   4   0   1   3
8     0   0   2   1   0   0
9     0   0   4   0   1   3
10    0   0   2   4   2   1
11    0   0   3   1   0   0
12    0   0   2   1   1   0
13    0   0   3   4   1   0
14    0   0   1   3   1   1
15    0   1   1   1   1   0
16    0   0   4   1   1   0
17    0   1   1   0   1   0
18    0   0   4   4   0   0
19    0   0   4   3   2   3
20    0   0   3   1   1   3
21    0   0   0   0   0   0
22    0   0   2   4   2   3
23    0   0   1   1   0   0
24    2   0   3   0   2   3
25    0   0   2   1   1   3
26    0   0   1   3   1   3
27    0   3   1   0   1   0
28    0   0   4   0   1   0
29    0   3   3   0   1   2
..   ..  ..  ..  ..  ..  ..
970   0   1   1   4   2   3
971   3   3   3   3   1   1
972   0   1   4   3   0   3
973   0   0   1   3 

In [0]:
network3= BayesianModel()
network3.add_nodes_from(['x1','x2','x3','x4','x5','x6'])
network3.add_edges_from([('x3','x2'),('x2','x5'),('x3','x6'),('x6','x1'),('x6','x4')])
network3.add_cpds(x3_cpd,x23_cpd,x52_cpd,x63_cpd,x16_cpd,x46_cpd)
network3.check_model()
infer3 = BayesianModelSampling(network3)
inference3=infer3.forward_sample(size=1000, return_type='dataframe')
print(inference3)
k2_3 = K2Score(inference3)
print(str(k2_3.score(network3)))


     x3  x6  x4  x2  x5  x1
0     1   1   0   0   0   0
1     2   2   0   4   3   0
2     0   1   0   3   0   0
3     0   1   3   1   3   0
4     2   1   0   0   3   2
5     0   4   3   4   3   0
6     0   4   3   4   1   0
7     1   2   0   0   2   0
8     1   2   1   1   3   0
9     1   3   3   4   0   0
10    1   1   0   1   1   3
11    2   3   1   4   0   0
12    0   2   1   1   1   1
13    1   2   0   1   2   3
14    1   2   0   4   0   2
15    0   3   0   1   2   0
16    1   3   0   1   0   0
17    2   1   0   0   2   0
18    1   3   0   1   3   0
19    0   3   0   0   2   0
20    1   4   0   1   0   0
21    2   4   3   0   3   3
22    1   3   0   4   0   0
23    1   1   0   3   2   0
24    1   3   3   1   3   0
25    2   3   1   0   3   0
26    1   3   3   2   1   0
27    1   3   0   1   0   0
28    0   1   0   4   2   0
29    2   3   0   4   0   3
..   ..  ..  ..  ..  ..  ..
970   2   4   0   4   3   0
971   1   3   0   1   0   0
972   1   4   3   0   0   3
973   1   2   0   0 

In [0]:
network4= BayesianModel()
network4.add_nodes_from(['x1','x2','x3','x4','x5','x6'])
network4.add_edges_from([('x6','x2'),('x2','x5'),('x5','x3'),('x6','x4'),('x4','x1')])
network4.add_cpds(x6_cpd,x26_cpd,x52_cpd,x35_cpd,x46_cpd,x14_cpd)
network4.check_model()
infer4 = BayesianModelSampling(network4)
inference4=infer4.forward_sample(size=1000, return_type='dataframe')
print(inference4)
k2_4 = K2Score(inference4)
print(str(k2_4.score(network4)))


     x6  x4  x2  x5  x3  x1
0     2   0   0   1   1   0
1     1   0   0   2   1   2
2     1   3   3   3   2   0
3     3   0   1   0   1   0
4     1   0   3   3   1   0
5     1   0   3   0   1   0
6     1   0   0   3   1   0
7     1   0   0   0   1   0
8     2   0   4   3   2   0
9     3   0   0   1   1   0
10    4   0   0   1   1   3
11    4   0   4   0   0   0
12    4   0   4   1   1   0
13    1   0   0   3   1   0
14    2   1   4   3   2   0
15    1   1   0   0   0   0
16    1   0   0   0   1   1
17    1   1   1   3   1   0
18    3   0   2   1   0   0
19    1   1   3   3   0   0
20    3   0   1   3   2   2
21    1   3   4   2   0   0
22    3   3   3   3   1   0
23    2   0   3   1   1   0
24    2   0   4   3   1   3
25    2   0   1   2   1   0
26    3   0   0   0   2   3
27    3   0   1   0   1   0
28    4   0   1   3   0   0
29    1   0   0   3   1   0
..   ..  ..  ..  ..  ..  ..
970   2   1   1   3   2   0
971   1   0   3   3   2   2
972   3   0   0   1   1   0
973   3   0   0   0 

In [0]:
data = [inference,inference1,inference2,inference3,inference4]
combined_infer = pd.concat(data,axis=0,sort=False)

In [0]:
K2 = K2Score(combined_infer)
print(str(K2.score(network)))
print(str(K2.score(network1)))
print(str(K2.score(network2)))
print(str(K2.score(network3)))
print(str(K2.score(network4)))

#Best Bayesian Network is network3 since its K2 score is the highest among the created networks
#Worst Bayesian Network is network4 since its K2 score is the lowest among the created networks


-31922.465946215812
-31906.205802519173
-31942.598709225465
-31906.077405075514
-32141.20688823206


In [0]:
# mle = MaximumLikelihoodEstimator(network3, inference)
# print(mle.estimate_cpd('x6'))  

+-------+----------------------+---------------------+---------------------+
| x3    | x3(0)                | x3(1)               | x3(2)               |
+-------+----------------------+---------------------+---------------------+
| x6(0) | 0.011834319526627219 | 0.01037037037037037 | 0.0                 |
+-------+----------------------+---------------------+---------------------+
| x6(1) | 0.2958579881656805   | 0.3214814814814815  | 0.24358974358974358 |
+-------+----------------------+---------------------+---------------------+
| x6(2) | 0.21301775147928995  | 0.1674074074074074  | 0.1794871794871795  |
+-------+----------------------+---------------------+---------------------+
| x6(3) | 0.20710059171597633  | 0.30814814814814817 | 0.33974358974358976 |
+-------+----------------------+---------------------+---------------------+
| x6(4) | 0.27218934911242604  | 0.1925925925925926  | 0.23717948717948717 |
+-------+----------------------+---------------------+---------------------+

## Markov network construction and inference.

In [0]:
from pgmpy.models import MarkovModel
from pgmpy.inference import BeliefPropagation
import time


mm = network3.to_markov_model()
# mm.nodes()
# mm.edges()
start = time.time()
bp = BeliefPropagation(network3)
mquery = bp.map_query(variables=['x1','x2','x3','x4','x5'],evidence={'x6':0})
end=time.time()
print("Computation Time for Best Bayesian Network converted to Markov Network :",end-start,"secs")
print(mquery)

start = time.time()
bp1 = BeliefPropagation(mm)
mquery1 = bp1.map_query(variables=['x1','x2','x3','x4','x5'],evidence={'x6':0})
end=time.time()
print("Computation Time for Best Bayesian Network: ",end-start,"secs")
print(mquery1)


#Markov Network takes more time than the corresponding Bayesian Network. It is slower.


Computation Time for Best Bayesian Network converted to Markov Network : 0.028000831604003906 secs
{'x1': 0, 'x2': 1, 'x3': 1, 'x4': 0, 'x5': 3}
Computation Time for Best Bayesian Network:  0.012248516082763672 secs
{'x1': 0, 'x2': 1, 'x3': 1, 'x4': 0, 'x5': 3}


In [0]:
#Using Hill Climb Search to estimate the best model

from pgmpy.estimators import HillClimbSearch

and_data = pd.read_csv('AND-Features.csv',header=0,index_col=0)
and_data.drop(['img_id'],inplace=True,axis=1,errors='ignore')
print(and_data)
hill_climb = HillClimbSearch(and_data,scoring_method=K2Score(and_data))
bestmodel = hill_climb.estimate()
print(bestmodel.edges())
k2score = K2Score(and_data)
print(str(k2score.score(bestmodel)))



      f1  f2  f3  f4  f5  f6  f7  f8  f9
0      2   1   1   0   2   2   0   2   2
1      2   1   1   0   2   2   0   1   2
2      2   1   1   3   2   2   0   2   2
3      1   1   1   0   2   2   0   2   2
4      2   1   1   0   2   2   0   0   2
5      2   1   1   3   2   2   0   1   2
6      2   1   1   0   2   2   0   3   2
7      1   1   1   0   2   2   0   1   2
8      1   1   1   3   2   2   0   2   2
9      2   1   1   3   2   2   0   0   2
10     3   1   1   0   2   2   0   2   2
11     2   1   1   3   2   2   0   3   2
12     1   1   1   0   2   2   0   0   2
13     2   1   1   0   2   2   1   2   2
14     1   1   1   3   2   2   0   1   2
15     1   1   1   0   2   2   0   3   2
16     3   1   1   0   2   2   0   1   2
17     3   1   1   3   2   2   0   2   2
18     2   1   1   0   2   2   1   1   2
19     1   1   1   3   2   2   0   0   2
20     2   1   1   3   2   2   1   2   2
21     2   1   1   1   2   2   0   2   2
22     1   1   1   3   2   2   0   3   2
23     3   1   1

In [0]:
from pgmpy.estimators import BayesianEstimator
from pgmpy.estimators import ConstraintBasedEstimator
from pgmpy.estimators import MaximumLikelihoodEstimator

#Bayesian Model is created using the edges given by Hill Climb Search and others using random edges. The other models have a lower 
#k2 score lower than the one estimated by Hill Climb Search. 

model = BayesianModel([('f3', 'f4'), ('f3', 'f9'), ('f3', 'f8'), ('f5', 'f9'), ('f5', 'f3'), ('f9', 'f8'), ('f9', 'f7'), ('f9', 'f1'), ('f9', 'f6'), ('f9', 'f2'), ('f9', 'f4')]) 
k2 = K2Score(and_data)
print(str(k2.score(model)))
#print(k2.local_score('f4', parents=['f3', 'f9']))



#est = ConstraintBasedEstimator(and_data)
# def is_independent(X, Y, Zs=[], significance_level=0.05):
#     return est.test_conditional_independence(X, Y, Zs)[1] >= significance_level
# print(is_independent('f4', 'f1'))    #independent
# print(is_independent('f4', 'f8'))          
# print(is_independent('f8', 'f3'))          
# print(is_independent('f1', 'f2', ['f4'])) 

est1 = BayesianEstimator(model, and_data)
print(est1.estimate_cpd('f9', prior_type='K2', equivalent_sample_size=10))  #Estimated conditional probability distribution
#of 'f9' based on the model and data-set.


model1 = BayesianModel([('f1', 'f2'), ('f1', 'f3'), ('f2', 'f4'), ('f4', 'f5'), ('f4', 'f8'), ('f3', 'f6'), ('f6', 'f9'), ('f9', 'f7')]) 
print(str(k2.score(model1)))


model2 = BayesianModel([('f1', 'f6'), ('f1', 'f8'), ('f6', 'f2'), ('f6', 'f3'), ('f8', 'f5'), ('f8', 'f4'), ('f2', 'f7'), ('f5', 'f9')]) 
print(str(k2.score(model2)))


model3 = BayesianModel([('f1', 'f9'), ('f1', 'f4'), ('f9', 'f7'), ('f4', 'f8'), ('f8', 'f6'), ('f6', 'f2'), ('f6', 'f5'), ('f5', 'f3')]) 
print(str(k2.score(model3)))


# mle = MaximumLikelihoodEstimator(model, and_data)
# print(mle.estimate_cpd('f9'))  





-9462.704892371386
+-------+-------+-------+----------------------+--------------------+---------------------+-------+---------------------+--------------------+-------+-------+-------+--------------------+
| f3    | f3(0) | f3(0) | f3(0)                | f3(0)              | f3(1)               | f3(1) | f3(1)               | f3(1)              | f3(2) | f3(2) | f3(2) | f3(2)              |
+-------+-------+-------+----------------------+--------------------+---------------------+-------+---------------------+--------------------+-------+-------+-------+--------------------+
| f5    | f5(0) | f5(1) | f5(2)                | f5(3)              | f5(0)               | f5(1) | f5(2)               | f5(3)              | f5(0) | f5(1) | f5(2) | f5(3)              |
+-------+-------+-------+----------------------+--------------------+---------------------+-------+---------------------+--------------------+-------+-------+-------+--------------------+
| f9(1) | 0.65  | 0.5   | 0.0210526315789